<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20190806 18:15:26.565" generator="Robot 2.8.5 (Python 2.7.12 on linux2)">
<suite source="/home/alan/PycharmProjects/demo_case/workflow_api_test/api_unit_test/domain_api_test" id="s1" name="Domain Api Test">
<suite source="/home/alan/PycharmProjects/demo_case/workflow_api_test/api_unit_test/domain_api_test/domain_api_test.robot" id="s1-s1" name="Domain Api Test">
<test id="s1-s1-t1" name="test_create_new_domain">
<kw type="setup" name="resource.Login">
<doc></doc>
<arguments>
</arguments>
<kw type="kw" name="${header} = Collections.Create Dictionary">
<doc>Creates and returns a dictionary based on given items.</doc>
<arguments>
<arg>Content-Type=application/json</arg>
</arguments>
<msg timestamp="20190806 18:15:26.763" level="INFO">${header} = {'Content-Type': u'application/json'}</msg>
<status status="PASS" endtime="20190806 18:15:26.763" starttime="20190806 18:15:26.762"></status>
</kw>
<kw type="kw" name="RequestsLibrary.Create Session">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>workflow</arg>
<arg>${WORKFLOW}</arg>
<arg>headers=${header}</arg>
</arguments>
<msg timestamp="20190806 18:15:26.765" level="INFO">Creating Session using : alias=workflow, url=http://workflow_host:9091, headers={'Content-Type': u'application/json'},                     cookies=None, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<msg timestamp="20190806 18:15:26.765" level="INFO">Argument types are:
&lt;type 'bool'&gt;</msg>
<status status="PASS" endtime="20190806 18:15:26.766" starttime="20190806 18:15:26.764"></status>
</kw>
<status status="PASS" endtime="20190806 18:15:26.766" starttime="20190806 18:15:26.761"></status>
</kw>
<kw type="kw" name="${result} = domain_resource.Create Domain">
<doc></doc>
<arguments>
<arg>${TEST_NAME}</arg>
</arguments>
<kw type="kw" name="BuiltIn.Log To Console">
<doc>Logs the given message to the console.</doc>
<arguments>
<arg>----------create domaim--------------</arg>
</arguments>
<status status="PASS" endtime="20190806 18:15:26.768" starttime="20190806 18:15:26.767"></status>
</kw>
<kw type="kw" name="${data} = Collections.Create Dictionary">
<doc>Creates and returns a dictionary based on given items.</doc>
<arguments>
<arg>name=${domain_name}</arg>
<arg>desc=${domain_name}</arg>
</arguments>
<msg timestamp="20190806 18:15:26.769" level="INFO">${data} = {'name': u'test_create_new_domain', 'desc': u'test_create_new_domain'}</msg>
<status status="PASS" endtime="20190806 18:15:26.769" starttime="20190806 18:15:26.768"></status>
</kw>
<kw type="kw" name="${guardian_params} = resource.Prepare GuardianParams">
<doc></doc>
<arguments>
</arguments>
<kw type="kw" name="${params} = Collections.Create Dictionary">
<doc>Creates and returns a dictionary based on given items.</doc>
<arguments>
<arg>guardian_access_token=${guardian_access_token}</arg>
</arguments>
<msg timestamp="20190806 18:15:26.771" level="INFO">${params} = {'guardian_access_token': 'token_content'}</msg>
<status status="PASS" endtime="20190806 18:15:26.771" starttime="20190806 18:15:26.771"></status>
</kw>
<msg timestamp="20190806 18:15:26.772" level="INFO">${guardian_params} = {'guardian_access_token': 'token_content'}</msg>
<status status="PASS" endtime="20190806 18:15:26.772" starttime="20190806 18:15:26.770"></status>
</kw>
<kw type="kw" name="${resp} = RequestsLibrary.Put Request">
<doc>Send a PUT request on the session object found using the</doc>
<arguments>
<arg>workflow</arg>
<arg>api/v1/domains</arg>
<arg>data=${data}</arg>
<arg>params=${guardian_params}</arg>
</arguments>
<msg timestamp="20190806 18:15:26.789" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fe9dc20f8d0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known',)': /api/v1/domains?guardian_access_token=token_content</msg>
<msg timestamp="20190806 18:15:26.994" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fe9dc20fad0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known',)': /api/v1/domains?guardian_access_token=token_content</msg>
<msg timestamp="20190806 18:15:27.400" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fe9dc20fcd0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known',)': /api/v1/domains?guardian_access_token=token_content</msg>
<msg timestamp="20190806 18:15:27.409" level="FAIL">ConnectionError: HTTPConnectionPool(host='workflow_host', port=9091): Max retries exceeded with url: /api/v1/domains?guardian_access_token=token_content (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fe9dc20fed0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known',))</msg>
<status status="FAIL" endtime="20190806 18:15:27.409" starttime="20190806 18:15:26.772"></status>
</kw>
<status status="FAIL" endtime="20190806 18:15:27.410" starttime="20190806 18:15:26.766"></status>
</kw>
<doc>TEST CREATE DOMAIN</doc>
<tags>
</tags>
<status status="FAIL" endtime="20190806 18:15:27.410" critical="yes" starttime="20190806 18:15:26.760">ConnectionError: HTTPConnectionPool(host='workflow_host', port=9091): Max retries exceeded with url: /api/v1/domains?guardian_access_token=token_content (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fe9dc20fed0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known',))</status>
</test>
<doc>domain api test</doc>
<metadata>
</metadata>
<status status="FAIL" endtime="20190806 18:15:27.411" starttime="20190806 18:15:26.609"></status>
</suite>
<doc></doc>
<metadata>
</metadata>
<status status="FAIL" endtime="20190806 18:15:27.413" starttime="20190806 18:15:26.566"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" pass="0" id="s1" name="Domain Api Test">Domain Api Test</stat>
<stat fail="1" pass="0" id="s1-s1" name="Domain Api Test">Domain Api Test.Domain Api Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20190806 18:15:26.789" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fe9dc20f8d0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known',)': /api/v1/domains?guardian_access_token=token_content</msg>
<msg timestamp="20190806 18:15:26.994" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fe9dc20fad0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known',)': /api/v1/domains?guardian_access_token=token_content</msg>
<msg timestamp="20190806 18:15:27.400" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fe9dc20fcd0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known',)': /api/v1/domains?guardian_access_token=token_content</msg>
</errors>
</robot>
